---
- name: Sync RHEL 8 repositories
  hosts: all
  become: true
  tasks:
    - name: Sync baseOS repository
      shell: rm -rf /var/cache/dnf
      shell: rm -rf /data/repos/rhel8.10
      shell: mkdir -p /data/repos
      shell: reposync -p /data/repos/rhel8.10/baseOS --download-metadata --repo=rhel-8-for-x86_64-baseos-rpms --newest-only > /var/log/reposync_baseOS.log 2>&1

    - name: Sync AppStream repository
      shell: reposync -p /data/repos/rhel8.10/AppStream --download-metadata --repo=rhel-8-for-x86_64-appstream-rpms --newest-only > /var/log/reposync_appstream.log 2>&1