name: Daily Python Script Execution for Cheatsheet

on:
  schedule:
    - cron: '50 1 * * *' # Runs at 7:20 AM IST (01:30 UTC)

permissions:
  contents: write # Allows write access to repository contents

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python Script
      run: |
        python pri/cs/cs.py

    - name: Commit and Push Report (if changed)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add pri/bm/bm.html

        # Only commit if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "Updated bookmarks"
          git push
        else
          echo "No changes to commit"
        fi
