name: Daily Python Script Execution

on:
  schedule:
    - cron: '0 23 * * *' # Runs at 5 AM IST (23:00 UTC)

permissions:
  contents: write # Allows write access to repository contents

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python myscript.py
        python system.py
        python news.py

    - name: Commit and Pusfindh Report
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add report.html system.html news.html
        git commit -m "Update daily reports"
        git push